// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSHjEMOT7rHQYJwXtGrOi_GQs4RrltNY',
    appId: '1:773236209016:web:d8dee10c3e5671e352448d',
    messagingSenderId: '773236209016',
    projectId: 'flutter-shop-c2713',
    authDomain: 'flutter-shop-c2713.firebaseapp.com',
    storageBucket: 'flutter-shop-c2713.appspot.com',
    measurementId: 'G-DYP1QBCWTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7CkGjR328G6fGuinBoy4JnSiYs0Tw-k',
    appId: '1:773236209016:android:815c58309b686fd352448d',
    messagingSenderId: '773236209016',
    projectId: 'flutter-shop-c2713',
    storageBucket: 'flutter-shop-c2713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInFb_Q6E1LgYX5NIuHdpRwoEEf4UlFj8',
    appId: '1:773236209016:ios:aed41754a9b1101552448d',
    messagingSenderId: '773236209016',
    projectId: 'flutter-shop-c2713',
    storageBucket: 'flutter-shop-c2713.appspot.com',
    iosBundleId: 'com.example.flutterShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInFb_Q6E1LgYX5NIuHdpRwoEEf4UlFj8',
    appId: '1:773236209016:ios:14b61f22922dd3af52448d',
    messagingSenderId: '773236209016',
    projectId: 'flutter-shop-c2713',
    storageBucket: 'flutter-shop-c2713.appspot.com',
    iosBundleId: 'com.example.flutterShop.RunnerTests',
  );
}
